# Generated by Django 5.1.7 on 2025-03-22 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_words_count', models.IntegerField(default=0, verbose_name='Nombre de mots total')),
                ('violent_words_count', models.IntegerField(default=0, verbose_name='Nombre de mots violents')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='PsychologicalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la thématique')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Thématique psychologique',
                'verbose_name_plural': 'Thématiques psychologiques',
            },
        ),
        migrations.CreateModel(
            name='ViolentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Mot violent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violent_words', to='chatbot.employee')),
            ],
            options={
                'verbose_name': 'Mot violent',
                'verbose_name_plural': 'Mots violents',
            },
        ),
        migrations.CreateModel(
            name='EmployeeThemeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name="Nombre d'occurrences")),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_counters', to='chatbot.employee')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.psychologicaltheme')),
            ],
            options={
                'verbose_name': 'Compteur de thématique',
                'verbose_name_plural': 'Compteurs de thématiques',
                'unique_together': {('employee', 'theme')},
            },
        ),
    ]
